import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const b=await chromium.launch({channel:'chromium'}),p=await b.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));
await p.addInitScript(()=>{window.__audioProbe={contexts:[],gains:[],sources:0,tones:[]};const Original=window.AudioContext;window.AudioContext=class extends Original{constructor(...args){super(...args);window.__audioProbe.contexts.push(this)}createGain(){const g=super.createGain();window.__audioProbe.gains.push(g);return g}createBufferSource(){window.__audioProbe.sources++;return super.createBufferSource()}createOscillator(){const o=super.createOscillator(),start=o.start.bind(o);o.start=(...args)=>{window.__audioProbe.tones.push({frequency:o.frequency.value,type:o.type});return start(...args)};return o}}});
await p.goto('http://127.0.0.1:5188/?qa');await p.locator('#start-button').click();await p.waitForTimeout(400);
const snap=()=>p.evaluate(()=>({contexts:window.__audioProbe.contexts.map(c=>c.state),sources:window.__audioProbe.sources,master:window.__audioProbe.gains[0].gain.value,rain:window.__audioProbe.gains[2].gain.value,tones:window.__audioProbe.tones}));
const started=await snap();assert.deepEqual(started.contexts,['running']);assert.equal(started.sources,3);assert(started.master>.5);
for(const kind of ['wood','stone']){await p.evaluate(kind=>{const h=window.__THREE_GAME_TEST_HOOKS__,r=h.state().resources.find(r=>r.kind===kind);h.teleport(r.x,r.z)},kind);await p.keyboard.press('e');await p.waitForTimeout(450);}
const gathered=await snap();assert(gathered.tones.some(t=>t.type==='triangle'));assert(gathered.tones.some(t=>t.type==='square'));
await p.locator('#sound-button').click();await p.waitForTimeout(600);const muted=await snap();assert(muted.master<.01);
await p.locator('#sound-button').click();await p.keyboard.press('Escape');await p.waitForTimeout(600);const paused=await snap();assert(paused.master<.01);
await p.keyboard.press('Escape');await p.evaluate(()=>window.__THREE_GAME_TEST_HOOKS__.setState('rain'));await p.waitForTimeout(1500);const rain=await snap();assert(rain.master>.5);assert(rain.rain>.2);assert.equal(rain.sources,3);assert.equal(rain.contexts.length,1);assert.equal(errors.length,0);
await fs.writeFile('artifacts/v3/audio-check.json',JSON.stringify({passed:true,checks:['gesture unlock','one context, three reusable ambience sources','distinct wood and stone tones','mute','pause silence','resume and rain ambience','no duplicate sources on state reset','no browser errors'],started,gathered,muted,paused,rain,errors},null,2));console.log('Audio lifecycle PASS');await b.close();
