import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const browser=await chromium.launch({channel:'chromium'});
const context=await browser.newContext({viewport:{width:1440,height:960}});
const page=await context.newPage();const errors=[],results=[];let current='';
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
const state=()=>page.evaluate(()=>window.__THREE_GAME_TEST_HOOKS__.state());
async function check(name,fn){current=name;await fn();results.push({name,passed:true});console.log('PASS',name);}
async function key(k){await page.keyboard.press(k);await page.waitForTimeout(180);}
async function advance(seconds){await page.evaluate(s=>window.__THREE_GAME_TEST_HOOKS__.advance(s),seconds);await page.waitForTimeout(180);}
async function close(){if(await page.locator('#game-panel').isVisible())await page.locator('#close-panel').click();}
async function panel(which){await close();await page.keyboard.press({crafting:'c',building:'b',inventory:'i',map:'m',skills:'k',saves:'F5'}[which]);await page.locator('#game-panel').waitFor({state:'visible'});}
async function teleport(x,z){await page.evaluate(({x,z})=>window.__THREE_GAME_TEST_HOOKS__.teleport(x,z),{x,z});await page.waitForTimeout(150);}
async function fixture({items={},tools={},buildings=[],x=0,z=65,discovered=[]}={}){await close();await page.evaluate(({items,tools,buildings,x,z,discovered})=>{const h=window.__THREE_GAME_TEST_HOOKS__,s=h.state();s.player.x=x;s.player.z=z;s.player.heading=0;s.player.health=100;s.player.thirst=90;s.player.hunger=90;s.player.warmth=95;s.inventory=items;s.equipment.tools=tools;s.equipment.active=null;s.cooldown=0;s.endgame.won=null;s.adventure.location="home";s.adventure.storm={phase:"calm",timer:10000,count:0,salvaged:0};s.progression.discovered=discovered;s.progression.perks=[];s.buildings=buildings.map((kind,i)=>({id:'fixture-'+kind,kind,x:x+(i%3)*5-5,z:z-Math.floor(i/3)*5-5,rotation:0,health:100,fuel:700,inventory:{},progress:0,water:0,planted:false,ready:false}));s.animals.forEach(a=>{a.hp=0;a.respawn=10000;});h.replace(s);},{items,tools,buildings,x,z,discovered});await page.waitForTimeout(150);}
async function craft(id){await panel('crafting');const button=page.locator(`[data-craft="${id}"]`);assert(await button.isEnabled(),`Recipe disabled ${id}: ${await button.textContent()}`);await button.click();await page.waitForTimeout(180);if(await page.evaluate(()=>!!window.__THREE_GAME_DIAGNOSTICS__.placement)){await page.keyboard.press('Enter');await page.waitForTimeout(180);}await close();}
async function gotoBuilding(kind){const b=(await state()).buildings.find(b=>b.kind===kind);assert(b,'missing '+kind);await teleport(b.x,b.z);return b;}
try{
await page.goto('http://127.0.0.1:5188/');await page.waitForTimeout(700);
await check('Production start and QA hooks gated',async()=>{assert.equal(await page.evaluate(()=>!!window.__THREE_GAME_TEST_HOOKS__),false);assert(await page.locator('#start-button').isVisible());});
await page.goto('http://127.0.0.1:5188/?qa');await page.locator('#start-button').click();await page.waitForTimeout(800);
await check('Keyboard movement and starter collection',async()=>{const before=await state();await key('e');assert((await state()).inventory.wood>=3);await page.keyboard.down('d');await page.waitForTimeout(700);await page.keyboard.up('d');const after=await state();assert(Math.hypot(after.player.x-before.player.x,after.player.z-before.player.z)>1);});
await check('Survival, food and source through real input',async()=>{await advance(30);const before=await state();assert(before.player.thirst<78);await key('q');assert((await state()).player.hunger>before.player.hunger);await teleport(-16,44);await key('e');assert((await state()).player.thirst>99);assert((await state()).progression.drank);});
await check('Fire recipe consumes materials and triggers autosave',async()=>{await fixture({items:{wood:10,stone:8,fiber:10},x:0,z:68});await craft('fire');const s=await state();assert.equal(s.inventory.wood,5);assert.equal(s.inventory.stone,5);assert(s.buildings.some(b=>b.kind==='fire'));assert(await page.evaluate(()=>!!localStorage.getItem('fernweh.v2.slot.0')));});
await check('Pause and journal freeze simulation',async()=>{await key('Escape');let before=(await state()).elapsed;await page.waitForTimeout(500);assert.equal((await state()).elapsed,before);await page.locator('#start-button').click();await panel('inventory');before=(await state()).elapsed;await page.waitForTimeout(500);assert.equal((await state()).elapsed,before);await close();});
await check('Workbench plus axe, pickaxe and hammer craft from UI',async()=>{await fixture({items:{wood:60,stone:50,rope:20,fiber:10},buildings:['shelter']});await craft('workbench');await gotoBuilding('workbench');await craft('axe');await craft('pickaxe');await craft('hammer');const s=await state();assert(s.equipment.tools.axe);assert(s.equipment.tools.pickaxe);assert(s.equipment.tools.hammer);});
await check('Axe increases wood yield, pickaxe increases stone yield in browser',async()=>{const before=await state();for(const kind of ['wood','stone']){const node=before.resources.find(r=>r.kind===kind&&r.remaining>0&&r.z>30);await teleport(node.x,node.z);const amount=(await state()).inventory[kind]||0;await advance(1);await key('e');assert(((await state()).inventory[kind]||0)-amount>=(kind==='wood'?5:4));}});
await check('Improved spear, trap and chest recipes',async()=>{await fixture({items:{wood:30,stone:20,rope:20,hardwood:15,flint:10,bone:5,berry:6},tools:{axe:90,pickaxe:90,hammer:100},buildings:['workbench']});await craft('improvedSpear');await craft('trap');await craft('chest');const s=await state();assert(s.equipment.tools.improvedSpear);assert(s.buildings.some(b=>b.kind==='trap'));assert(s.buildings.some(b=>b.kind==='chest'));});
await check('Chest UI deposit and withdrawal',async()=>{await gotoBuilding('chest');await key('e');await page.locator('[data-action="deposit"][data-item="wood"][data-amount="5"]').click();assert.equal((await state()).buildings.find(b=>b.kind==='chest').inventory.wood,5);await page.locator('[data-action="withdraw"][data-item="wood"][data-amount="1"]').click();assert.equal((await state()).buildings.find(b=>b.kind==='chest').inventory.wood,4);await close();});
let saved;
await check('Manual slot saves full state with metadata',async()=>{await page.evaluate(()=>{const h=window.__THREE_GAME_TEST_HOOKS__,s=h.state();s.player.x=11;s.player.z=60;s.progression.xp.survival=47;s.progression.perks=['endurance'];s.progression.discovered.push('north');s.equipment.tools.axe=43;h.replace(s);});await panel('saves');await page.locator('[data-save-slot="1"]').click();saved=await state();const raw=await page.evaluate(()=>JSON.parse(localStorage.getItem('fernweh.v2.slot.1')));assert.equal(raw.version,3);assert(raw.checksum);assert.equal(raw.state.player.x,11);assert(raw.state.buildings.some(b=>b.kind==='chest'));});
await check('Reload and load restore position, inventory, containers, progression, tools',async()=>{await page.reload();await page.locator('#overlay [data-panel="saves"]').click();await page.locator('[data-load-slot="1"]').click();await page.waitForTimeout(200);assert(await page.locator('#game-panel').isHidden());const loaded=await state();assert(Math.abs(loaded.player.x-saved.player.x)<.01);assert.deepEqual(loaded.inventory,saved.inventory);assert.equal(loaded.equipment.tools.axe,43);assert.equal(loaded.progression.xp.survival,47);assert(loaded.progression.perks.includes('endurance'));assert.equal(loaded.buildings.find(b=>b.kind==='chest').inventory.wood,4);});
await check('Overwrite confirmation, three manual slots and delete',async()=>{await panel('saves');await page.locator('[data-save-slot="1"]').click();assert(await page.locator('#confirm-action').isVisible());await page.locator('#confirm-action').click();await page.locator('[data-save-slot="2"]').click();await page.locator('[data-save-slot="3"]').click();await page.locator('[data-delete-slot="2"]').click();await page.locator('#confirm-action').click();assert.equal(await page.evaluate(()=>localStorage.getItem('fernweh.v2.slot.2')),null);assert(await page.evaluate(()=>!!localStorage.getItem('fernweh.v2.slot.3')));await close();});
await check('Pause journal actions remain functional',async()=>{await close();await page.evaluate(()=>{const h=window.__THREE_GAME_TEST_HOOKS__,s=h.state();s.progression.xp.gathering=50;s.progression.perks=[];h.replace(s);});await key('Escape');await page.locator('#overlay [data-panel="skills"]').click();await page.locator('[data-action="perk"][data-id="lumber"]').click();assert((await state()).progression.perks.includes('lumber'));await close();await page.locator('#start-button').click();});
await check('Recipe availability and capacity guards shown in UI',async()=>{await fixture({items:{wood:480}});await panel('crafting');assert(await page.locator('[data-craft="axe"]').isDisabled());assert(await page.locator('[data-craft="signal"]').isDisabled());await panel('inventory');assert((await page.locator('.panel-intro').textContent()).includes('24 / 24'));await close();});
await check('Fishing timing via E catches a fish',async()=>{await fixture({items:{},tools:{fishingRod:100},x:38,z:72});await key('e');assert((await state()).fishing.active);await advance((await state()).fishing.biteAt+.1);await key('e');assert.equal((await state()).inventory.fish,1);});
await check('Cooking, food consumption and rain water catcher',async()=>{await fixture({items:{meat:2,fish:2,wood:5},tools:{canteen:100},buildings:['cooker','raincatcher']});await gotoBuilding('cooker');await craft('cookedMeat');assert.equal((await state()).inventory.cookedMeat,1);await panel('inventory');await page.locator('[data-action="eat"][data-item="cookedMeat"]').click();assert(!(await state()).inventory.cookedMeat);await close();await page.evaluate(()=>{const h=window.__THREE_GAME_TEST_HOOKS__,s=h.state();s.weather={kind:'rain',remaining:1000,wind:.6};h.replace(s);});await advance(60);assert((await state()).buildings.find(b=>b.kind==='raincatcher').water>2);await gotoBuilding('raincatcher');await key('e');assert((await state()).inventory.water>=2);});
await check('Trap produces loot and planted farm matures',async()=>{await fixture({items:{seed:2},buildings:['trap','farm']});await gotoBuilding('farm');await key('e');assert((await state()).buildings.find(b=>b.kind==='farm').planted);await advance(490);assert((await state()).buildings.find(b=>b.kind==='farm').ready);await key('e');assert((await state()).inventory.potato>=5);await gotoBuilding('trap');await key('e');assert((await state()).inventory.meat>=1);});
await check('Sleep skips night and advances production',async()=>{await fixture({items:{},buildings:['bed','trap']});await page.evaluate(()=>{const h=window.__THREE_GAME_TEST_HOOKS__,s=h.state();s.cycle=.82;s.player.hunger=100;s.player.thirst=100;s.player.health=70;h.replace(s);});await gotoBuilding('bed');const before=(await state()).elapsed;await key('e');await page.locator('[data-action="sleep"]').click();const s=await state();assert(s.elapsed>before+400);assert(s.player.health>70);assert(s.player.rested>0);await close();});
await check('Discovery and skill purchase persist',async()=>{await fixture();await teleport(-51,-17);await advance(1);assert((await state()).progression.discovered.includes('swamp'));await page.evaluate(()=>{const h=window.__THREE_GAME_TEST_HOOKS__,s=h.state();s.progression.xp.gathering=50;h.replace(s);});await panel('skills');await page.locator('[data-action="perk"][data-id="lumber"]').click();assert((await state()).progression.perks.includes('lumber'));await panel('map');assert((await page.locator('#panel-body').textContent()).includes('Nebelbruch'));await close();});
await check('Signal route requires summit and reaches victory',async()=>{await fixture({items:{hardwood:16,stone:18,resin:6,coal:6,metal:4},tools:{metalPickaxe:100},buildings:['advancedBench'],x:0,z:-34,discovered:['mountain','north','cave']});await craft('signal');await page.evaluate(()=>{const h=window.__THREE_GAME_TEST_HOOKS__,s=h.state();s.weather={kind:'clear',remaining:1000,wind:.2};s.animals.forEach(a=>a.respawn=10000);h.replace(s);});await advance(301);assert.equal((await state()).endgame.won,'signal');assert(await page.locator('#overlay').isVisible());});
await check('New game confirmation preserves manual saves',async()=>{await page.locator('#new-button').click();await page.locator('#confirm-action').click();assert.equal((await state()).buildings.length,0);assert(await page.evaluate(()=>!!localStorage.getItem('fernweh.v2.slot.1')));});
await check('Raft route buys all six stages, storm blocks and calm departs',async()=>{await fixture({items:{hardwood:40,rope:30,plank:24,metal:12,boatPart:5,cloth:10,hide:3,resin:8,water:10,ration:10},tools:{metalAxe:100,hammer:100,repairKit:100,canteen:100,backpack:100},buildings:['raft','advancedBench','dryer'],discovered:['north','cave']});await gotoBuilding('raft');await key('e');for(let i=0;i<6;i++){await page.locator('[data-action="raft"]').click();assert.equal((await state()).endgame.raftStage,i+1);}await close();await page.evaluate(()=>{const h=window.__THREE_GAME_TEST_HOOKS__,s=h.state();s.weather.kind='storm';h.replace(s);});await key('e');await page.locator('[data-action="depart"]').click();assert.equal((await state()).endgame.won,null);await close();await page.evaluate(()=>{const h=window.__THREE_GAME_TEST_HOOKS__,s=h.state();s.weather.kind='clear';h.replace(s);});await key('e');await page.locator('[data-action="depart"]').click();assert.equal((await state()).endgame.won,null);assert.equal((await state()).adventure.location,'sea');});
await check('Defeat and manual load recover a journey',async()=>{await key('Escape');await page.locator('#new-button').click();await page.locator('#confirm-action').click();await page.evaluate(()=>window.__THREE_GAME_TEST_HOOKS__.scenario('near-death'));await advance(1);assert(await page.locator('#new-button').isVisible());await page.locator('#overlay [data-panel="saves"]').click();await page.locator('[data-load-slot="1"]').click();await page.locator('#confirm-action').click();assert((await state()).player.health>0);});
await check('45-second real autosave interval',async()=>{await close();await fixture({items:{wood:7}});await page.evaluate(()=>window.__THREE_GAME_TEST_HOOKS__.save(0));const before=await page.evaluate(()=>JSON.parse(localStorage.getItem('fernweh.v2.slot.0')).savedAt);await page.waitForFunction(before=>JSON.parse(localStorage.getItem('fernweh.v2.slot.0')).savedAt!==before,before,{timeout:65000});assert((await state()).elapsed>=44);});
await check('Corrupt save is displayed safely and cannot be loaded',async()=>{await page.evaluate(()=>localStorage.setItem('fernweh.v2.slot.3','{broken'));await page.reload();await page.locator('#overlay [data-panel="saves"]').click();assert(await page.locator('[data-load-slot="3"]').isDisabled());assert((await page.locator('#panel-body').textContent()).includes('Nicht lesbar'));});
await close();await page.locator('#start-button').click();await page.waitForTimeout(400);
await check('Desktop UI no horizontal overflow',async()=>{for(const which of ['inventory','crafting','map','saves']){await panel(which);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await page.locator('#game-panel').evaluate(el=>el.scrollWidth>el.clientWidth+1),false);}await page.screenshot({path:'artifacts/v3/regression-desktop-saves.png'});await close();});
const diagnostics=await page.evaluate(()=>window.__THREE_GAME_DIAGNOSTICS__);assert(diagnostics.renderer.calls<320);await context.close();
const mobile=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true,deviceScaleFactor:2});const m=await mobile.newPage();m.on('pageerror',e=>errors.push(e.message));await m.goto('http://127.0.0.1:5188/?qa');await m.locator('#start-button').tap();await m.waitForTimeout(500);
await check('Mobile touch movement, inventory, crafting and save slots',async()=>{const before=await m.evaluate(()=>window.__THREE_GAME_TEST_HOOKS__.state().player);const pad=m.locator('[data-key="d"]'),box=await pad.boundingBox();await m.mouse.move(box.x+box.width/2,box.y+box.height/2);await m.mouse.down();await m.waitForTimeout(650);await m.mouse.up();const after=await m.evaluate(()=>window.__THREE_GAME_TEST_HOOKS__.state().player);assert(Math.hypot(after.x-before.x,after.z-before.z)>1);for(const selector of ['#inventory-button','#craft-button']){await m.locator(selector).tap();assert.equal(await m.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await m.locator('#close-panel').tap();}await m.locator('#inventory-button').tap();await m.locator('#panel-nav [data-panel="saves"]').tap();await m.locator('[data-save-slot="1"]').tap();assert(await m.evaluate(()=>!!localStorage.getItem('fernweh.v2.slot.1')));await m.screenshot({path:'artifacts/v3/regression-mobile-saves.png'});await m.locator('#close-panel').tap();await m.screenshot({path:'artifacts/v3/regression-mobile-play.png'});});
await mobile.close();assert.deepEqual(errors,[]);await fs.writeFile('artifacts/v3/regression-playtest.json',JSON.stringify({results,errors,diagnostics},null,2));console.log('ALL PASS',results.length);
}catch(e){console.error('FAIL',current,e);await page.screenshot({path:'artifacts/v3/regression-failure.png'}).catch(()=>{});await fs.writeFile('artifacts/v3/regression-playtest-failure.json',JSON.stringify({current,results,errors,error:String(e)},null,2));process.exitCode=1;}finally{await browser.close();}
