import {chromium} from '@playwright/test';import fs from 'node:fs/promises';import assert from 'node:assert/strict';
const b=await chromium.launch({channel:'chromium'}),p=await b.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));
await p.goto('http://127.0.0.1:5188/');assert.equal(await p.evaluate(()=>typeof window.__THREE_GAME_TEST_HOOKS__),'undefined');assert.equal(await p.evaluate(()=>typeof window.__THREE_GAME_DIAGNOSTICS__),'undefined');
await p.goto('http://127.0.0.1:5188/?qa');await p.locator('#start-button').click();const resets=[];
for(let i=0;i<24;i++){await p.evaluate(()=>window.__THREE_GAME_TEST_HOOKS__.setState('upgraded-base'));await p.waitForTimeout(100);resets.push(await p.evaluate(()=>window.__THREE_GAME_DIAGNOSTICS__.renderer));}
const late=resets.slice(5);assert(Math.max(...late.map(r=>r.geometries))-Math.min(...late.map(r=>r.geometries))<=3);assert(late.every(r=>r.textures<=2));
const mobile=await b.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});await mobile.goto('http://127.0.0.1:5188/?qa');await mobile.locator('#start-button').click();await mobile.evaluate(()=>window.__THREE_GAME_TEST_HOOKS__.setState('dead'));await mobile.waitForTimeout(200);
const layout=await mobile.evaluate(()=>{const s=document.querySelector('#overlay'),h=document.querySelector('#overlay-title'),r=h.getBoundingClientRect();return {width:innerWidth,scroll:s.scrollWidth,client:s.clientWidth,titleLeft:r.left,titleRight:r.right,textWidth:h.scrollWidth,titleWidth:h.clientWidth};});assert(layout.scroll<=layout.client+1);assert(layout.titleRight<=layout.width);assert(layout.textWidth<=layout.titleWidth+1);await mobile.screenshot({path:'artifacts/v3/mobile-defeat-fixed.png'});assert.equal(errors.length,0);
await fs.writeFile('artifacts/v3/stability.json',JSON.stringify({passed:true,checks:['production hooks absent','24 repeated world resets with bounded renderer resources','mobile defeat text and controls fit'],resets,layout,errors},null,2));console.log('Stability and mobile defeat PASS');await b.close();
