import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const browser=await chromium.launch({channel:'chromium'});
const context=await browser.newContext({viewport:{width:1440,height:960},recordVideo:{dir:'artifacts/motion',size:{width:960,height:640}}});
const page=await context.newPage();const errors=[];const results=[];
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
const snapshot=()=>page.evaluate(()=>window.__THREE_GAME_DIAGNOSTICS__);
async function check(name,fn){await fn();results.push({name,passed:true});console.log('PASS',name);}
async function key(k,ms=120){await page.keyboard.down(k);await page.waitForTimeout(ms);await page.keyboard.up(k);}
async function waitGame(seconds){const t=(await snapshot()).elapsed;await page.waitForFunction(t=>window.__THREE_GAME_DIAGNOSTICS__.elapsed>=t,t+seconds,{timeout:30000});}
async function walkTo(x,z){let held=[];for(let i=0;i<90;i++){const s=await snapshot(),dx=x-s.player.x,dz=z-s.player.z;if(Math.hypot(dx,dz)<1.15)break;const sx=dx*.824-dz*.566,sz=dx*.566+dz*.824;const next=[];if(Math.abs(sx)>.4)next.push(sx>0?'d':'a');if(Math.abs(sz)>.4)next.push(sz>0?'s':'w');for(const k of held)if(!next.includes(k))await page.keyboard.up(k);for(const k of next)if(!held.includes(k))await page.keyboard.down(k);held=next;await page.waitForTimeout(160);}for(const k of held)await page.keyboard.up(k);await page.waitForTimeout(150);const s=await snapshot();assert(Math.hypot(x-s.player.x,z-s.player.z)<2.2,`Could not reach ${x},${z}`);}
try{
await page.goto('http://127.0.0.1:5188/?qa');await page.locator('#start-button').click();await page.waitForTimeout(1500);
await check('Real E input collects starter wood',async()=>{await key('e');await waitGame(.5);assert((await snapshot()).inventory.wood>=3);});
await check('Real movement, stone collection, campfire economy',async()=>{await key('e');await waitGame(.5);await walkTo(-2,9);await key('e');await waitGame(.5);let s=await snapshot();assert(s.inventory.stone>=3);assert(s.inventory.wood>=5);await walkTo(0,14);await key('b');await page.locator('[data-craft="fire"]').click();await waitGame(.2);s=await snapshot();assert.equal(s.buildings.filter(b=>b.kind==='fire').length,1);assert.equal(s.inventory.wood,1);assert.equal(s.inventory.stone,0);await key('b');});
await check('Q eats and changes hunger',async()=>{const before=await snapshot();await key('q');await waitGame(.2);const after=await snapshot();assert.equal(after.inventory.berry,before.inventory.berry-1);assert(after.hunger>before.hunger);});
await check('Pause freezes simulation and resumes',async()=>{await key('Escape');const before=await snapshot();await page.waitForTimeout(700);assert.equal((await snapshot()).elapsed,before.elapsed);await page.locator('#start-button').click();await waitGame(.2);assert.equal((await snapshot()).phase,'play');});
await check('Spring restores thirst through E',async()=>{await walkTo(-9,3);const before=await snapshot();await key('e');await waitGame(.2);assert((await snapshot()).thirst>before.thirst);});
await check('Insufficient crafting does not charge inventory',async()=>{const before=await snapshot();await key('b');await page.locator('[data-craft="shelter"]').click();await waitGame(.2);assert.deepEqual((await snapshot()).inventory,before.inventory);await key('b');});
// Controlled later-stage setup; actions remain real buttons/keys.
await page.evaluate(()=>window.__THREE_GAME_TEST_HOOKS__.scenario('craft'));
await check('Spear recipe and three-hit hunt',async()=>{await key('b');await page.locator('[data-craft="spear"]').click();await key('b');await waitGame(.2);assert((await snapshot()).hasSpear);await page.evaluate(()=>{window.__THREE_GAME_TEST_HOOKS__.teleport(0,4);window.__THREE_GAME_TEST_HOOKS__.scenario('hunt');});for(let i=0;i<3;i++){await key('e');await waitGame(.5);}assert.equal((await snapshot()).inventory.meat,5);});
await check('Cooking meat and refueling at campfire',async()=>{const fire=(await snapshot()).buildings.find(b=>b.kind==='fire');await page.evaluate(p=>window.__THREE_GAME_TEST_HOOKS__.teleport(p.x,p.z),fire);const before=await snapshot();await key('q');await waitGame(.2);assert.equal((await snapshot()).inventory.meat,before.inventory.meat-1);await key('e');await waitGame(.5);const after=await snapshot();assert.equal(after.inventory.wood,before.inventory.wood-1);assert(after.buildings.find(b=>b.kind==='fire').fuel>before.buildings.find(b=>b.kind==='fire').fuel);});
await check('Shelter and signal build; rescue reaches win',async()=>{await page.evaluate(()=>window.__THREE_GAME_TEST_HOOKS__.teleport(-5,10));await key('b');await page.locator('[data-craft="shelter"]').click();await waitGame(.2);assert((await snapshot()).buildings.some(b=>b.kind==='shelter'));await key('b');await page.evaluate(()=>window.__THREE_GAME_TEST_HOOKS__.teleport(5,10));await key('b');await page.locator('[data-craft="signal"]').click();await waitGame(.2);assert((await snapshot()).buildings.some(b=>b.kind==='signal'));await key('b');await page.screenshot({path:'artifacts/camp.png'});await page.evaluate(()=>window.__THREE_GAME_TEST_HOOKS__.scenario('rescue-nearly-complete'));await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__.phase==='win',{timeout:10000});});
await check('Win restart and survival failure retry',async()=>{await page.locator('#start-button').click();await waitGame(.2);assert.equal((await snapshot()).buildings.length,0);await page.evaluate(()=>window.__THREE_GAME_TEST_HOOKS__.scenario('near-death'));await page.waitForFunction(()=>window.__THREE_GAME_DIAGNOSTICS__.phase==='dead',{timeout:10000});await page.screenshot({path:'artifacts/dead.png'});await page.locator('#start-button').click();await waitGame(.2);assert.equal((await snapshot()).health,100);assert.equal((await snapshot()).phase,'play');});
const metrics=await snapshot();const gl=await page.evaluate(()=>{const gl=document.querySelector('canvas').getContext('webgl2');const e=gl.getExtension('WEBGL_debug_renderer_info');return e?gl.getParameter(e.UNMASKED_RENDERER_WEBGL):'unknown';});
await context.close();
const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:2});const m=await mobile.newPage();m.on('pageerror',e=>errors.push(e.message));await m.goto('http://127.0.0.1:5188/?qa');await m.locator('#start-button').tap();await m.waitForTimeout(1200);
await check('Mobile touch movement, action and responsive HUD',async()=>{const before=await m.evaluate(()=>window.__THREE_GAME_DIAGNOSTICS__.player);const pad=m.locator('[data-key="d"]');const box=await pad.boundingBox();await m.mouse.move(box.x+box.width/2,box.y+box.height/2);await m.mouse.down();await m.waitForTimeout(900);await m.mouse.up();const after=await m.evaluate(()=>window.__THREE_GAME_DIAGNOSTICS__.player);assert(Math.hypot(after.x-before.x,after.z-before.z)>1);await m.locator('[data-key="e"]').tap();await m.screenshot({path:'artifacts/mobile.png'});assert.equal(await m.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await m.locator('#build-button').tap();assert(await m.locator('[data-craft="signal"]').isVisible());await m.locator('#close-build').tap();});
await mobile.close();assert.deepEqual(errors,[]);await fs.writeFile('artifacts/playtest.json',JSON.stringify({results,errors,gpu:gl,metrics},null,2));console.log('ALL PASS',results.length);
}catch(error){console.error(error);await fs.writeFile('artifacts/playtest-failure.json',JSON.stringify({results,errors,error:String(error)},null,2));process.exitCode=1;}finally{await browser.close();}
