import type {
  ExpeditionNode,
  Islet,
  SecretSpot,
  GameMode,
} from "./adventure-types";
export const MODE_LABELS: Record<GameMode, string> = {
  cozy: "Inselruhe",
  survival: "Überleben",
  expedition: "Expedition",
};
export const ISLETS: Islet[] = [
  {
    id: "reef",
    name: "Korallenwacht",
    x: 180,
    z: 35,
    radius: 28,
    dock: { x: 157, z: 35 },
    description: "Ein versunkenes Observatorium und eine Linse im Riff.",
  },
  {
    id: "ember",
    name: "Glutinsel",
    x: -180,
    z: -100,
    radius: 30,
    dock: { x: -155, z: -100 },
    description: "Die erkaltete Schmiede birgt eine Signalbatterie.",
  },
  {
    id: "lighthouse",
    name: "Letztes Licht",
    x: 30,
    z: -220,
    radius: 26,
    dock: { x: 30, z: -198 },
    description: "Setze das Leuchtfeuer instand und rufe die Rettung.",
  },
];
export const EXPEDITIONS: ExpeditionNode[] = [
  {
    id: "shore-1",
    quest: "Flaschenpost",
    step: 0,
    title: "Die Flaschenpost",
    description: "Eine Zeichnung zeigt die Quelle und einen eingeritzten Baum.",
    clue: "Suche die eingeritzte Palme westlich der Quelle.",
    x: 9,
    z: 72,
    island: "home",
    reward: { cloth: 2 },
  },
  {
    id: "shore-2",
    quest: "Flaschenpost",
    step: 1,
    title: "Drei Kerben",
    description:
      "Unter der Rinde steht: Wenn der Schatten das Wasser berührt, folge dem Steinbogen.",
    clue: "Am südlichen Steinbogen liegt ein Vorrat.",
    x: -24,
    z: 48,
    island: "home",
    requires: "tool:knife",
    reward: { fiber: 6 },
  },
  {
    id: "shore-3",
    quest: "Flaschenpost",
    step: 2,
    title: "Vorrat der Gestrandeten",
    description:
      "Du findest versiegelte Vorräte und einen Bauplan für sparsame Reparaturen.",
    clue: "Die ersten Bewohner haben dieselbe Hoffnung getragen.",
    x: -27,
    z: 67,
    island: "home",
    reward: { ration: 3, water: 4, rope: 3 },
  },
  {
    id: "jungle-1",
    quest: "Grünes Archiv",
    step: 0,
    title: "Verlassenes Forschungslager",
    description: "Eine Botanikerin sammelte hier seltene Samen.",
    clue: "Folge den roten Stoffstreifen nach Osten.",
    x: 25,
    z: 23,
    island: "home",
    reward: { herb: 2 },
  },
  {
    id: "jungle-2",
    quest: "Grünes Archiv",
    step: 1,
    title: "Wurzelkammer",
    description: "Eine verschlossene Kiste wartet zwischen den Wurzeln.",
    clue: "Das letzte Beet liegt nördlich des Lagers.",
    x: 40,
    z: 13,
    island: "home",
    requires: "tool:axe",
    reward: { seed: 4 },
  },
  {
    id: "jungle-3",
    quest: "Grünes Archiv",
    step: 2,
    title: "Saatgutbibliothek",
    description:
      "Gerettete Samen und Feldnotizen verbessern deine Ernten dauerhaft.",
    clue: "Belohnung: Botanisches Wissen und Saatgut.",
    x: 21,
    z: 0,
    island: "home",
    reward: { seed: 8, herb: 4, potato: 4 },
  },
  {
    id: "marsh-1",
    quest: "Lichter im Moor",
    step: 0,
    title: "Versunkener Steg",
    description: "Harzreste führen zu einem verlassenen Köhlerplatz.",
    clue: "Suche westlich der dunklen Wasserstelle.",
    x: -40,
    z: -8,
    island: "home",
    reward: { resin: 2 },
  },
  {
    id: "marsh-2",
    quest: "Lichter im Moor",
    step: 1,
    title: "Der Köhlerplatz",
    description: "Im Ofen liegen brauchbare Kohlen unter schwerem Gestein.",
    clue: "Nachts zeigen Glühwürmchen den letzten Hinweis.",
    x: -61,
    z: -17,
    island: "home",
    requires: "tool:pickaxe",
    reward: { coal: 6 },
  },
  {
    id: "marsh-3",
    quest: "Lichter im Moor",
    step: 2,
    title: "Glühwürmchenpfad",
    description: "Unter den Lichtern liegt die versiegelte Harztruhe.",
    clue: "Harz zum Abdichten deiner künftigen Seereise.",
    x: -47,
    z: -30,
    island: "home",
    requires: "night",
    reward: { resin: 10, cloth: 4 },
  },
  {
    id: "peak-1",
    quest: "Der Wetterwart",
    step: 0,
    title: "Wetterstation",
    description: "Ein zerbrochener Windmesser kündigt große Stürme an.",
    clue: "Die Messnotizen liegen am Westhang.",
    x: 0,
    z: -26,
    island: "home",
    reward: { metal: 2 },
  },
  {
    id: "peak-2",
    quest: "Der Wetterwart",
    step: 1,
    title: "Geröllnotizen",
    description: "Löse die Metallkassette aus dem Geröll.",
    clue: "Trage die Notizen zum Gipfel zurück.",
    x: -14,
    z: -36,
    island: "home",
    requires: "tool:pickaxe",
    reward: { ore: 5 },
  },
  {
    id: "peak-3",
    quest: "Der Wetterwart",
    step: 2,
    title: "Windregister",
    description:
      "Du entzifferst sichere Wetterfenster und erhältst robuste Segeltücher.",
    clue: "Die See belohnt Vorbereitung.",
    x: 4,
    z: -43,
    island: "home",
    requires: "tool:hammer",
    reward: { cloth: 8, rope: 4 },
  },
  {
    id: "cave-1",
    quest: "Unter dem Basalt",
    step: 0,
    title: "Verblasste Grubenkarte",
    description: "Hinter dem Eingang wartet eine markierte Erzader.",
    clue: "Eine Fackel macht die Markierungen sichtbar.",
    x: 37,
    z: -25,
    island: "home",
    requires: "tool:torch",
    reward: { coal: 3 },
  },
  {
    id: "cave-2",
    quest: "Unter dem Basalt",
    step: 1,
    title: "Die blaue Ader",
    description: "Zwischen den Steinen steckt eine alte Werkzeugkiste.",
    clue: "Der Schacht endet an einer vermauerten Nische.",
    x: 48,
    z: -31,
    island: "home",
    requires: "tool:pickaxe",
    reward: { ore: 8 },
  },
  {
    id: "cave-3",
    quest: "Unter dem Basalt",
    step: 2,
    title: "Bergmanns Vermächtnis",
    description: "Du birgst Metall und erlernst haltbarere Werkzeugpflege.",
    clue: "Werkzeuge verlieren künftig langsamer Haltbarkeit.",
    x: 47,
    z: -40,
    island: "home",
    requires: "tool:hammer",
    reward: { metal: 5, flint: 6 },
  },
  {
    id: "wreck-1",
    quest: "Die Morgenstern",
    step: 0,
    title: "Logbuch der Morgenstern",
    description: "Die Besatzung suchte drei Inseln und einen alten Leuchtturm.",
    clue: "Untersuche die aufgerissene Kajüte.",
    x: 1,
    z: -68,
    island: "home",
    reward: { cloth: 3 },
  },
  {
    id: "wreck-2",
    quest: "Die Morgenstern",
    step: 1,
    title: "Die Kapitänskajüte",
    description: "Ein verkeiltes Fach schützt die Seekarte.",
    clue: "Die letzte Fracht liegt nördlich des Bugs.",
    x: 10,
    z: -77,
    island: "home",
    requires: "tool:hammer",
    reward: { boatPart: 2 },
  },
  {
    id: "wreck-3",
    quest: "Die Morgenstern",
    step: 2,
    title: "Die Seekarte",
    description:
      "Korallenwacht, Glutinsel und Letztes Licht sind nun auf deiner Seekarte markiert.",
    clue: "Baue ein Floß und segle zu den drei Inseln.",
    x: -5,
    z: -85,
    island: "home",
    requires: "low-tide",
    reward: { boatPart: 3, cloth: 6, rope: 4 },
  },
  {
    id: "reef-1",
    quest: "Die versunkene Linse",
    step: 0,
    title: "Korallenobservatorium",
    description: "Die Sternwarte verlor ihre Linse in einem Beben.",
    clue: "Suche östlich der alten Säulen.",
    x: 175,
    z: 36,
    island: "reef",
    reward: { water: 5, coconut: 5 },
  },
  {
    id: "reef-2",
    quest: "Die versunkene Linse",
    step: 1,
    title: "Flutkammer",
    description: "Bei Ebbe erreichst du die unversehrte Leuchtturmlinse.",
    clue: "Fasse die Linse am Signalpodest ein.",
    x: 190,
    z: 43,
    island: "reef",
    requires: "low-tide",
    reward: { metal: 3 },
  },
  {
    id: "reef-3",
    quest: "Die versunkene Linse",
    step: 2,
    title: "Sternenlinse",
    description: "Du sicherst die Linse für den Leuchtturm.",
    clue: "Auf der Glutinsel fehlt noch die Energiequelle.",
    x: 179,
    z: 22,
    island: "reef",
    cost: { rope: 2 },
    reward: { ration: 4, water: 5 },
  },
  {
    id: "ember-1",
    quest: "Herz aus Glut",
    step: 0,
    title: "Die alte Schmiede",
    description: "Ein Wartungsbuch beschreibt eine salzwasserfeste Batterie.",
    clue: "Suche in der östlichen Werkstatt.",
    x: -176,
    z: -97,
    island: "ember",
    reward: { water: 5, potato: 5 },
  },
  {
    id: "ember-2",
    quest: "Herz aus Glut",
    step: 1,
    title: "Erkalteter Tiegel",
    description: "Befreie das Batteriegehäuse aus der Schlacke.",
    clue: "Setze die Kontakte an der Werkbank instand.",
    x: -189,
    z: -110,
    island: "ember",
    requires: "tool:metalPickaxe",
    reward: { metal: 5, coal: 5 },
  },
  {
    id: "ember-3",
    quest: "Herz aus Glut",
    step: 2,
    title: "Signalbatterie",
    description: "Mit neuen Kontakten lebt die Batterie wieder auf.",
    clue: "Bringe Linse und Batterie nach Letztes Licht.",
    x: -171,
    z: -115,
    island: "ember",
    cost: { metal: 3, cloth: 2 },
    reward: { ration: 4, water: 5 },
  },
  {
    id: "light-1",
    quest: "Letztes Licht",
    step: 0,
    title: "Das schweigende Licht",
    description: "Das Leuchtfeuer braucht eine Linse und eine Batterie.",
    clue: "Schließe die Expeditionen auf Korallenwacht und Glutinsel ab.",
    x: 29,
    z: -211,
    island: "lighthouse",
    requires: "voyage-relics",
    reward: { water: 5, coconut: 5 },
  },
  {
    id: "light-2",
    quest: "Letztes Licht",
    step: 1,
    title: "Licht im Turm",
    description: "Du verbindest die alte Technik und richtest die Optik aus.",
    clue: "Am höchsten Podest kannst du die Rettung rufen.",
    x: 22,
    z: -224,
    island: "lighthouse",
    requires: "tool:repairKit",
    cost: { metal: 3, rope: 2 },
    reward: { ration: 3 },
  },
  {
    id: "light-3",
    quest: "Letztes Licht",
    step: 2,
    title: "Eine Antwort am Horizont",
    description:
      "Ein Schiff antwortet. Du kannst jetzt die Rettung rufen oder weiterleben.",
    clue: "Am Leuchtfeuer: Rettung rufen.",
    x: 35,
    z: -229,
    island: "lighthouse",
  },
];
export const SECRETS: SecretSpot[] = [
  {
    id: "tide-cache",
    title: "Vergrabene Seemannskiste",
    x: 28,
    z: 79,
    island: "home",
    condition: "low-tide",
    reward: { rope: 5, cloth: 4 },
  },
  {
    id: "moon-herbs",
    title: "Mondblüten",
    x: -50,
    z: 3,
    island: "home",
    condition: "night",
    reward: { herb: 8, seed: 4 },
  },
  {
    id: "storm-hold",
    title: "Freigelegte Wrackladung",
    x: 20,
    z: -74,
    island: "home",
    condition: "after-storm",
    reward: { boatPart: 3, metal: 5 },
  },
  {
    id: "old-cache",
    title: "Vorrat am Wurzelstein",
    x: 45,
    z: 30,
    island: "home",
    condition: "always",
    reward: { ration: 3, water: 3 },
  },
  {
    id: "reef-pearl",
    title: "Schatz der Gezeiten",
    x: 185,
    z: 21,
    island: "reef",
    condition: "low-tide",
    reward: { metal: 6, cloth: 4 },
  },
  {
    id: "ember-cache",
    title: "Versiegelter Schacht",
    x: -194,
    z: -96,
    island: "ember",
    condition: "always",
    reward: { ore: 10, coal: 8 },
  },
];
