import type { ItemId, Inventory, Recipe, Perk } from "./types";
export const DAY_LENGTH = 1200;
const item = (name: string, category: string, description: string) => ({
  name,
  category,
  description,
});
export const ITEMS: Record<ItemId, ReturnType<typeof item>> = {
  wood: item("Holz", "Ressourcen", "Treibholz und Bauholz; Brennstoff."),
  hardwood: item(
    "Hartholz",
    "Ressourcen",
    "Mit einer Axt im Dschungel gewinnen.",
  ),
  stone: item("Stein", "Ressourcen", "Werkzeuge, Feuerstellen und Bauwerke."),
  flint: item("Feuerstein", "Ressourcen", "Scharfe Klingen aus den Bergen."),
  fiber: item("Fasern", "Ressourcen", "Zu Seil flechten."),
  berry: item("Beeren", "Nahrung", "Kleine, sofort essbare Stärkung."),
  coconut: item("Kokosnuss", "Nahrung", "Stillt Hunger und Durst."),
  herb: item("Heilkraut", "Nahrung", "Heilt Wunden und Vergiftung."),
  meat: item("Rohes Fleisch", "Nahrung", "Vor dem Essen besser kochen."),
  cookedMeat: item("Gebratenes Fleisch", "Nahrung", "Sättigend und sicher."),
  hide: item("Tierhaut", "Ressourcen", "Bett und Ausrüstung."),
  bone: item("Knochen", "Ressourcen", "Für Speere und Werkzeuge."),
  rope: item("Seil", "Ressourcen", "Aus Fasern geflochten."),
  plank: item("Bretter", "Ressourcen", "An der Werkbank verarbeitet."),
  metal: item("Metall", "Ressourcen", "Am Wrack bergen oder Erz schmelzen."),
  ore: item("Erz", "Ressourcen", "Mit Spitzhacke aus der Höhle."),
  coal: item("Kohle", "Ressourcen", "Für die Schmelze und das Signalfeuer."),
  fish: item(
    "Roher Fisch",
    "Nahrung",
    "An Küstenstellen angeln; vor Verzehr kochen.",
  ),
  cookedFish: item("Gegarter Fisch", "Nahrung", "Leichte, nahrhafte Mahlzeit."),
  water: item(
    "Trinkwasservorrat",
    "Nahrung",
    "Mit einem Wasserbehälter abfüllen.",
  ),
  resin: item(
    "Harz",
    "Ressourcen",
    "Im Nebelbruch sammeln; Dichtstoff und Feuerhilfe.",
  ),
  seed: item(
    "Samen",
    "Ressourcen",
    "Beim Beerensammeln finden; im Beet pflanzen.",
  ),
  potato: item("Kartoffeln", "Nahrung", "Aus dem eigenen Beet."),
  ration: item(
    "Reiseproviant",
    "Nahrung",
    "Am Trockengestell hergestellt; für lange Reisen.",
  ),
  cloth: item(
    "Stoff",
    "Ressourcen",
    "Am Nordwrack bergen; Segel und Ausrüstung.",
  ),
  boatPart: item(
    "Wrackbeschläge",
    "Ressourcen",
    "Seltene Bauteile vom Nordwrack.",
  ),
};
export const RECIPES: Recipe[] = [
  {
    id: "knife",
    name: "Steinklinge",
    description: "Mehr Pflanzen und bessere Jagdbeute.",
    tier: 0,
    category: "Werkzeuge",
    cost: { stone: 2, fiber: 2 },
    tool: "knife",
  },
  {
    id: "spear",
    name: "Einfacher Speer",
    description: "Abstand zu Wildschweinen halten.",
    tier: 0,
    category: "Waffen",
    cost: { wood: 4, stone: 2, fiber: 2 },
    tool: "spear",
  },
  {
    id: "torch",
    name: "Fackel",
    description: "Licht und Wärme; Zugang zu dunklen Erzadern.",
    tier: 0,
    category: "Überleben",
    cost: { wood: 2, fiber: 3 },
    tool: "torch",
  },
  {
    id: "fire",
    name: "Lagerfeuer",
    description: "Wärmt; mit Holz nachlegen. Startet mit drei Minuten Glut.",
    tier: 0,
    category: "Bauen",
    cost: { wood: 5, stone: 3 },
    building: "fire",
  },
  {
    id: "shelter",
    name: "Unterschlupf",
    description: "Schutz vor Regen und ein Platz zum Schlafen.",
    tier: 0,
    category: "Bauen",
    cost: { wood: 8, fiber: 6 },
    building: "shelter",
  },
  {
    id: "rope",
    name: "Seil flechten",
    description: "Vier Fasern ergeben zwei Seile.",
    tier: 0,
    category: "Werkzeuge",
    cost: { fiber: 4 },
    output: { rope: 2 },
  },
  {
    id: "workbench",
    name: "Werkbank",
    description: "Schaltet präzise Werkzeuge und Lagerbau frei.",
    tier: 0,
    category: "Bauen",
    cost: { wood: 12, stone: 6, rope: 2 },
    building: "workbench",
    requires: ["built:shelter"],
  },
  {
    id: "axe",
    name: "Steinaxt",
    description: "Deutlich bessere Holzausbeute und Zugang zu Hartholz.",
    tier: 1,
    category: "Werkzeuge",
    cost: { wood: 5, stone: 5, rope: 2 },
    tool: "axe",
    station: "workbench",
  },
  {
    id: "pickaxe",
    name: "Spitzhacke",
    description: "Mehr Stein; Erz und Kohle abbauen.",
    tier: 1,
    category: "Werkzeuge",
    cost: { wood: 5, stone: 6, rope: 2 },
    tool: "pickaxe",
    station: "workbench",
  },
  {
    id: "hammer",
    name: "Hammer",
    description: "Ermöglicht fortgeschrittene Gebäude.",
    tier: 1,
    category: "Werkzeuge",
    cost: { wood: 4, stone: 4, rope: 1 },
    tool: "hammer",
    station: "workbench",
  },
  {
    id: "improvedSpear",
    name: "Jagdspeer",
    description: "Höherer Schaden und 3,8 Meter Reichweite.",
    tier: 1,
    category: "Waffen",
    cost: { hardwood: 5, flint: 3, rope: 2, bone: 2 },
    tool: "improvedSpear",
    station: "workbench",
    requires: ["tool:axe"],
  },
  {
    id: "canteen",
    name: "Wasserbehälter",
    description: "An Quellen und Regenfängern Wasservorräte füllen.",
    tier: 1,
    category: "Überleben",
    cost: { hide: 2, rope: 2, resin: 1 },
    tool: "canteen",
    station: "workbench",
  },
  {
    id: "fishingRod",
    name: "Angel",
    description: "An markierten Küstenstellen auswerfen; beim Biss E drücken.",
    tier: 1,
    category: "Werkzeuge",
    cost: { wood: 5, rope: 3, bone: 1 },
    tool: "fishingRod",
    station: "workbench",
  },
  {
    id: "plank",
    name: "Bretter sägen",
    description: "Vier Holz ergeben drei Bretter.",
    tier: 1,
    category: "Werkzeuge",
    cost: { wood: 4 },
    output: { plank: 3 },
    station: "workbench",
    requires: ["tool:axe"],
  },
  {
    id: "chest",
    name: "Lagerkiste",
    description: "32 Lagerplätze für je 20 Gegenstände.",
    tier: 1,
    category: "Bauen",
    cost: { wood: 10, rope: 2 },
    building: "chest",
    station: "workbench",
  },
  {
    id: "bed",
    name: "Fellbett",
    description: "Erholsamer Schlaf und längerer Ausgeruht-Bonus.",
    tier: 1,
    category: "Bauen",
    cost: { wood: 8, hide: 3, fiber: 6 },
    building: "bed",
    station: "workbench",
  },
  {
    id: "cooker",
    name: "Kochstation",
    description: "Fleisch und Fisch sicher zubereiten; braucht Brennholz.",
    tier: 1,
    category: "Bauen",
    cost: { stone: 10, wood: 6 },
    building: "cooker",
    station: "workbench",
  },
  {
    id: "trap",
    name: "Kleintierfalle",
    description: "Fängt alle drei Minuten Beute. Mit E einsammeln.",
    tier: 1,
    category: "Bauen",
    cost: { wood: 6, rope: 3, berry: 2 },
    building: "trap",
    station: "workbench",
  },
  {
    id: "cookedMeat",
    name: "Fleisch braten",
    description: "Rohes Fleisch zu einer kräftigen Mahlzeit braten.",
    tier: 1,
    category: "Nahrung",
    cost: { meat: 1 },
    output: { cookedMeat: 1 },
    station: "cooker",
  },
  {
    id: "cookedFish",
    name: "Fisch garen",
    description: "Fisch sicher zubereiten.",
    tier: 1,
    category: "Nahrung",
    cost: { fish: 1 },
    output: { cookedFish: 1 },
    station: "cooker",
  },
  {
    id: "advancedBench",
    name: "Verbesserte Werkbank",
    description: "Metallhandwerk und Konstruktion für die Flucht.",
    tier: 2,
    category: "Bauen",
    cost: { plank: 12, hardwood: 8, metal: 4, rope: 4 },
    building: "advancedBench",
    station: "workbench",
    requires: ["tool:hammer", "discovered:north"],
  },
  {
    id: "furnace",
    name: "Schmelzofen",
    description: "Erz und Kohle in Metall verarbeiten.",
    tier: 2,
    category: "Bauen",
    cost: { stone: 18, flint: 6 },
    building: "furnace",
    station: "workbench",
    requires: ["tool:hammer", "discovered:cave"],
  },
  {
    id: "metal",
    name: "Metall schmelzen",
    description: "Zwei Erz und eine Kohle ergeben zwei Metall.",
    tier: 2,
    category: "Werkzeuge",
    cost: { ore: 2, coal: 1 },
    output: { metal: 2 },
    station: "furnace",
  },
  {
    id: "metalAxe",
    name: "Metallaxt",
    description: "Noch mehr Holz und schonender Hartholzabbau.",
    tier: 2,
    category: "Werkzeuge",
    cost: { metal: 6, hardwood: 4, rope: 2 },
    tool: "metalAxe",
    station: "advancedBench",
  },
  {
    id: "metalPickaxe",
    name: "Metallspitzhacke",
    description: "Große Ausbeute bei Gestein und Erz.",
    tier: 2,
    category: "Werkzeuge",
    cost: { metal: 7, hardwood: 4, rope: 2 },
    tool: "metalPickaxe",
    station: "advancedBench",
  },
  {
    id: "backpack",
    name: "Rucksack",
    description: "Erweitert das Inventar von 24 auf 36 Stapelplätze.",
    tier: 2,
    category: "Überleben",
    cost: { hide: 4, cloth: 3, rope: 4 },
    tool: "backpack",
    station: "workbench",
  },
  {
    id: "raincatcher",
    name: "Regenfänger",
    description: "Sammelt Regen für Trinkwasser und Vorräte.",
    tier: 2,
    category: "Bauen",
    cost: { plank: 6, cloth: 3, rope: 3 },
    building: "raincatcher",
    station: "workbench",
    requires: ["tool:hammer"],
  },
  {
    id: "dryer",
    name: "Trockengestell",
    description: "Verarbeitet gegarte Nahrung zu Reiseproviant.",
    tier: 2,
    category: "Bauen",
    cost: { hardwood: 6, rope: 4 },
    building: "dryer",
    station: "workbench",
    requires: ["tool:hammer"],
  },
  {
    id: "ration",
    name: "Reiseproviant trocknen",
    description: "Zwei gegarte Fleischstücke und Beeren ergeben drei Rationen.",
    tier: 2,
    category: "Nahrung",
    cost: { cookedMeat: 2, berry: 3 },
    output: { ration: 3 },
    station: "dryer",
  },
  {
    id: "fishRation",
    name: "Fischproviant trocknen",
    description: "Auch Angler können haltbaren Reiseproviant herstellen.",
    tier: 2,
    category: "Nahrung",
    cost: { cookedFish: 2, berry: 3 },
    output: { ration: 3 },
    station: "dryer",
  },
  {
    id: "bigTrap",
    name: "Große Tierfalle",
    description: "Fängt größere Beute. Jagdkenntnis beschleunigt Fallen.",
    tier: 2,
    category: "Bauen",
    cost: { hardwood: 10, metal: 3, rope: 5 },
    building: "bigTrap",
    station: "advancedBench",
    requires: ["tool:hammer"],
  },
  {
    id: "farm",
    name: "Pflanzbeet",
    description: "Ein Samen wächst in acht Minuten; Regen hilft.",
    tier: 2,
    category: "Bauen",
    cost: { plank: 5, fiber: 6 },
    building: "farm",
    station: "workbench",
    requires: ["tool:hammer"],
  },
  {
    id: "cabin",
    name: "Waldhütte",
    description: "Robuste Unterkunft, Wärmeschutz und guter Schlaf.",
    tier: 2,
    category: "Bauen",
    cost: { plank: 18, hardwood: 12, rope: 8, metal: 4 },
    building: "cabin",
    station: "advancedBench",
    requires: ["tool:hammer"],
  },
  {
    id: "repairKit",
    name: "Reparaturwerkzeug",
    description: "Für ein seetüchtiges Floß; günstigere Werkzeugreparaturen.",
    tier: 3,
    category: "Werkzeuge",
    cost: { metal: 4, hardwood: 3, cloth: 2 },
    tool: "repairKit",
    station: "advancedBench",
  },
  {
    id: "raft",
    name: "Floßbauplatz",
    description: "An der Küste errichten. Sechs Baustufen bis zur Abfahrt.",
    tier: 3,
    category: "Flucht",
    cost: { wood: 12, rope: 4 },
    building: "raft",
    requires: ["built:advancedBench", "tool:hammer", "discovered:north"],
  },
  {
    id: "signal",
    name: "Signalfeuer",
    description:
      "Am Windgrat errichten; insgesamt fünf klare Minuten sammeln. Bewölkung pausiert den Fortschritt.",
    tier: 3,
    category: "Flucht",
    cost: { hardwood: 16, stone: 18, resin: 6, coal: 6, metal: 4 },
    building: "signal",
    requires: [
      "built:advancedBench",
      "tool:metalPickaxe",
      "discovered:mountain",
      "discovered:north",
      "discovered:cave",
    ],
  },
];
export const RAFT_STAGES: Array<{
  name: string;
  cost: Inventory;
  description: string;
}> = [
  {
    name: "Schwimmkörper",
    cost: { hardwood: 18, rope: 8 },
    description: "Mit Metallaxt und Hammer kräftige Stämme verbinden.",
  },
  {
    name: "Deck",
    cost: { plank: 24, metal: 6 },
    description: "Ein tragfähiges Deck aus gesägten Brettern.",
  },
  {
    name: "Mast und Verstrebungen",
    cost: { hardwood: 12, rope: 8, boatPart: 2 },
    description: "Wrackbeschläge sichern den Mast.",
  },
  {
    name: "Segel",
    cost: { cloth: 10, rope: 6, hide: 3 },
    description: "Stoff vom Nordwrack fängt den Wind.",
  },
  {
    name: "Abdichten",
    cost: { resin: 8, metal: 6, boatPart: 3 },
    description: "Mit Reparaturwerkzeug alle Verbindungen abdichten.",
  },
  {
    name: "Vorräte verstauen",
    cost: { water: 10, ration: 10 },
    description: "Trinkwasser und Proviant für die Überfahrt lagern.",
  },
];
export const PERKS: Perk[] = [
  {
    id: "endurance",
    skill: "survival",
    name: "Langer Atem",
    description: "25 % weniger Sprintverbrauch.",
    cost: 35,
  },
  {
    id: "thrifty",
    skill: "survival",
    name: "Genügsam",
    description: "15 % weniger Hunger und Durst.",
    cost: 60,
  },
  {
    id: "warmblood",
    skill: "survival",
    name: "Wetterfest",
    description: "30 % weniger Wärmeverlust.",
    cost: 85,
  },
  {
    id: "lumber",
    skill: "gathering",
    name: "Holzkenntnis",
    description: "Ein zusätzliches Holz pro Sammelaktion.",
    cost: 35,
  },
  {
    id: "miner",
    skill: "gathering",
    name: "Gesteinskunde",
    description: "Ein zusätzlicher Stein oder Erz pro Abbau.",
    cost: 60,
  },
  {
    id: "botany",
    skill: "gathering",
    name: "Pflanzenkunde",
    description: "Ein zusätzlicher Pflanzenertrag und mehr Ernte.",
    cost: 85,
  },
  {
    id: "hunter",
    skill: "hunting",
    name: "Sicherer Stoß",
    description: "20 % mehr Speerschaden.",
    cost: 30,
  },
  {
    id: "trapper",
    skill: "hunting",
    name: "Fährtenleser",
    description: "Fallen arbeiten 25 % schneller.",
    cost: 55,
  },
  {
    id: "angler",
    skill: "hunting",
    name: "Ruhige Hand",
    description: "Längeres Bissfenster und zwei Fische.",
    cost: 80,
  },
  {
    id: "durable",
    skill: "crafting",
    name: "Sorgfalt",
    description: "Werkzeuge verschleißen 30 % langsamer.",
    cost: 35,
  },
  {
    id: "chef",
    skill: "crafting",
    name: "Lagerkoch",
    description: "Gekochte Nahrung sättigt 25 % mehr.",
    cost: 60,
  },
  {
    id: "builder",
    skill: "crafting",
    name: "Zimmermann",
    description:
      "Neue Bauwerke erhalten 30 % mehr Stabilität; Reparaturen kosten weniger.",
    cost: 85,
  },
];
